<?php
App::uses('AppController', 'Controller');

/**
 * Letters Controller
 *
 * @property Letter $Letter
 * @property PaginatorComponent $Paginator
 * @property SessionComponent $Session
 */
class LettersController extends AppController
{

    /**
     * Components
     *
     * @var array
     */
    public $components = array('Paginator', 'Session');

    /**
     * Breadcrumb for all
     *
     * @var array
     */
    private $breadCrumb = array(
        0 => array(
            'title' => 'Surat Tugas',
            'controller' => 'letters',
            'action' => '/'
        )
    );

    public function index()
    {

    }

    public function indexExpose()
    {
    }

    public function addExpose()
    {
        $title_for_layout = 'Tambah SP2 Ekspose';
        $breadCrumb = $this->breadCrumb;
        $breadCrumb[1] = array(
            'title' => 'SP2 Ekspose',
            'controller' => 'letters',
            'action' => 'indexExpose'
        );
        $breadCrumb[2] = array(
            'title' => 'Tambah',
            'controller' => 'letters',
            'action' => 'addExpose'
        );

        $data = array();
        if ($this->request->is(array('post', 'put'))) {
            $start = $this->request->data['Letter']['start'];
            $end = $this->request->data['Letter']['end'];
            $date = $this->request->data['Letter']['date'];
            $description = $this->request->data['Letter']['description'];
            $personInCharge = explode(',', $this->request->data['Letter']['personInCharge']);
            $employees = explode(',', $this->request->data['Letter']['employees']);
            $dateArr = explode('-', $date);
            $name = $this->letterCategorySP2Expose . $dateArr[1] . '/' . $dateArr[0];

            //first save to activities table
            //2nd save to letters table
            //3rd save to evidences table
            //4th create file
            //5th give a download link for pdf file generated by no 4
        }

        $departements = $this->Letter->Departement->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'NOT' => array(
                    'Departement.id' => $this->departementSekretariat,
                    'Departement.parent_id' => null,
                    'Departement.active' => 0
                )
            ),
            'fields' => array('Departement.id', 'Departement.name')
        ));

        $this->set(compact('title_for_layout', 'breadCrumb', 'departements', 'data'));
    }

    public function isLetterNotExists() {
        $description = trim(strtolower($this->request->data['description']));
        $description = '%' . $description . '%';
        $start = trim($this->request->data['start']);

        empty($start) ? $start = date('Y-m-d') : $start = $start;

        $countData = $this->Letter->Activity->find('count', array(
            'conditions' => array(
                'Activity.active' => 1,
                'Activity.start' => $start,
                'Activity.description LIKE' => $description
            )
        ));

        $countData > 0 ? $data = false : $data = true;

        $this->set(compact('data'));
        $this->set('_serialize', 'data');
    }

    private function createPdf($data = null) {
        empty($data['Letter']['start']) ? $start = date('Y-m-d') : $start = $data['Letter']['start'];
        empty($data['Letter']['end']) ? $end = date('Y-m-d') : $end = $data['Letter']['end'];
        empty($data['Letter']['date']) ? $date = date('Y-m-d') : $date = $data['Letter']['date'];

        $personInCharge = explode(',', $data['Letter']['personInCharge']);
        $employees = explode(',', $data['Letter']['employees']);
        $departement = explode(',', $data['Letter']['departements']);

        $description = $data['Letter']['description'];
    }

    public function test() {
        $this->autoRender = false;
        $departementId = array(3,4);
        $departements = $this->Letter->Departement->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'Departement.id' => $departementId,
                'Departement.active' => true
            ),
            'order' => array(
                'Departement.name ASC'
            )
        ));

        print_r($departements);
        //$this->set(compact('officers'));
    }

    public function create_pdf(){
        $city = $this->city;
        $date = date('Y-m-d');
        $arrDate = explode('-', $date);
        $month = $this->monthTranslation[(int)$arrDate[1]]['indonesianLong'];
        $description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat';
        $officerId = array(61, 3);//person in charge
        $userId = array(1,5,6,7,8);//audience
        $allId = array_merge($officerId, $userId);
        $departementId = array(3, 4);
        $officers = $this->Letter->Uploader->User->Usercareerview->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'Usercareerview.id' => $officerId,
                'Usercareerview.levelactive' => true,
                'Usercareerview.roleactive' => true,
                'Usercareerview.departementactive' => true,
                'Usercareerview.levelend' => null,
                'Usercareerview.roleend' => null
            ),
            'order' => array(
                'Usercareerview.role_id DESC',
                'Usercareerview.level_id DESC',
                'Usercareerview.name ASC'
            )
        ));

        $users = $this->Letter->Uploader->User->Usercareerview->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                //'Usercareerview.id' => $userId,
                'Usercareerview.levelactive' => true,
                'Usercareerview.roleactive' => true,
                'Usercareerview.departementactive' => true,
                'Usercareerview.levelend' => null,
                'Usercareerview.roleend' => null,
                'NOT' => array('Usercareerview.id' => 3)
            ),
            'order' => array(
                'Usercareerview.role_id DESC',
                'Usercareerview.level_id DESC',
                'Usercareerview.name ASC'
            )
        ));

        //for master of the office
        $this->Letter->Departement->ChiefsDepartement->unbindModel(array(
            'belongsTo' => array(
                'Departement'
            )
        ));
        $master = $this->Letter->Departement->ChiefsDepartement->find('first', array(
            'recursive' => 2,
            'conditions' => array(
                'ChiefsDepartement.departement_id' => $this->departementPerwakilan,
                'ChiefsDepartement.end' => null,
                'ChiefsDepartement.active' => true
            )
        ));

        //for departement to send
        $departements = $this->Letter->Departement->Userdepartementview->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'Userdepartementview.user_id' => $officerId,
                'Userdepartementview.active' => true
            ),
            'fields' => array('Userdepartementview.departementdescription'),
            'group' => array('Userdepartementview.departement_id'),
            'order' => array('Userdepartementview.departementdescription ASC')
        ));

        $roles = $this->Letter->Departement->User->Userroleview->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'Userroleview.user_id' => $allId,
                'Userroleview.active' => true
            ),
            'fields' => array('Userroleview.rolename'),
            'group' => array('Userroleview.role_id'),
            'order' => array('Userroleview.role_id ASC')
        ));

        $this->set(compact('date','arrDate', 'month', 'description', 'officers', 'users', 'city', 'master', 'departements', 'roles'));

        $this->layout = '/pdf/default';

        $this->render('/Pdf/my_pdf_view');

    }
/**
 * CREATE VIEW userlevelviews AS SELECT lu.id AS id, lu.level_id AS level_id, lu.user_id AS user_id, lu.start AS start, lu.end AS end, lu.active AS active, u.name AS name, u.active AS useractive, l.name AS levelname, l.description AS leveldescription, l.active AS levelactive
 */
}