<?php
App::uses('AppController', 'Controller');

/**
 * Letters Controller
 *
 * @property Letter $Letter
 * @property PaginatorComponent $Paginator
 * @property SessionComponent $Session
 */
class LettersController extends AppController
{

    /**
     * Components
     *
     * @var array
     */
    public $components = array('Paginator', 'Session');

    /**
     * Breadcrumb for all
     *
     * @var array
     */
    private $breadCrumb = array(
        0 => array(
            'title' => 'Surat Penugasan',
            'controller' => 'letters',
            'action' => '/'
        )
    );

    public function index()
    {

    }

    public function indexExpose()
    {
        $title_for_layout = 'SP2 Ekspose';
        $breadCrumb = $this->breadCrumb;
        $breadCrumb[1] = array(
            'title' => 'SP2 Ekspose',
            'controller' => 'letters',
            'action' => 'indexExpose'
        );

        $this->set(compact('title_for_layout', 'breadCrumb', 'data'));
    }

    public function addExpose()
    {
        $title_for_layout = 'Tambah SP2 Ekspose';
        $breadCrumb = $this->breadCrumb;
        $breadCrumb[1] = array(
            'title' => 'SP2 Ekspose',
            'controller' => 'letters',
            'action' => 'indexExpose'
        );
        $breadCrumb[2] = array(
            'title' => 'Tambah',
            'controller' => 'letters',
            'action' => 'addExpose'
        );

        $data = array();
        if ($this->request->is(array('post', 'put'))) {
            empty($this->request->data['Letter']['start']) ? $start = date('Y-m-d') : $start = $this->request->data['Letter']['start'];
            empty($this->request->data['Letter']['end']) ? $end = date('Y-m-d') : $end = $this->request->data['Letter']['end'];
            empty($this->request->data['Letter']['date']) ? $date = date('Y-m-d') : $date = $this->request->data['Letter']['date'];
            $description = $this->request->data['Letter']['description'];
            $personInCharge = explode(',', $this->request->data['Letter']['personInCharge']);
            $employees = explode(',', $this->request->data['Letter']['employees']);
            $dateArr = explode('-', $date);
            $name = $this->letterSP2FormatNo . $dateArr[1] . '/' . $dateArr[0];

            //1st save to activities table
            $dataToActivities = array(
                'name' => $name,
                'description' => $description,
                'start' => $start,
                'end' => $end,
                'uploader_id' => $this->Auth->user('id')
            );
            if(!$this->addExposeAddToActivities($dataToActivities)){
                $this->Session->setFlash(__('Kegiatan tidak dapat disimpan, silahkan ulangi.'));
                return $this->redirect(array('action' => 'addExpose'));
            }

            //2nd save to activities_users table
            $dataToActivitiesUsers = array(
                'activity_id' => $this->Letter->Activity->getInsertID(),
                'personInCharge' => $personInCharge,
                'employees' => $employees
            );
            if(!$this->addExposeAddToActivitiesUsers($dataToActivitiesUsers)) {
                $this->Session->setFlash(__('Peserta tidak dapat disimpan, silahkan ulangi.'));
                return $this->redirect(array('action' => 'addExpose'));
            }

            //3rd save to letters table
            $dataToLetters = array(
                'activity_id' => $this->Letter->Activity->getInsertID(),
                'type_id' => $this->typeSP2,
                'lettercategory_id' => $this->letterCategorySP2Expose,
                'name' => $name,
                'date' => $date,
                'uploader_id' => $this->Auth->user('id')
            );
            if(!$this->addExposeAddToLetters($dataToLetters)) {
                $this->Session->setFlash(__('Draft tidak dapat disimpan, silahkan ulangi.'));
                return $this->redirect(array('action' => 'addExpose'));
            }

            //4th save to evidences table
            $dataToEvidences = array(
                'name' => $name,
                'extension' => 'pdf',
                'type_id' => $this->typeSP2,
                'uploader_id' => $this->Auth->user('id'),
                'activity_id' => $this->Letter->Activity->getInsertID()
            );
            if(!$this->addExposeAddToEvidences($dataToEvidences)) {
                $this->Session->setFlash(__('Berkas Draft tidak dapat disimpan, silahkan ulangi.'));
                return $this->redirect(array('action' => 'addExpose'));
            }

            //5th create file
            $fileName = $this->Letter->Activity->Evidence->getInsertID();
            $this->addExposeCreatePdf($date, $description, $personInCharge, $employees, $fileName);

            //6th give a download link for pdf file generated by no 4
            //@todo create download link by add session
            return $this->redirect(array('action' => 'indexExpose'));
        }

        $departements = $this->Letter->Departement->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'NOT' => array(
                    'Departement.id' => $this->departementSekretariat,
                    'Departement.parent_id' => null,
                    'Departement.active' => 0
                )
            ),
            'fields' => array('Departement.id', 'Departement.name')
        ));

        $this->set(compact('title_for_layout', 'breadCrumb', 'departements', 'data'));
    }

    private function addExposeAddToActivities($data) {
        if(!empty($data)) {
            $this->Letter->Activity->create();

            if($this->Letter->Activity->save($data)) {
                return true;
            }
        }
        return false;
    }

    private function addExposeAddToActivitiesUsers($data) {
        if(!empty($data)) {
            $countPersonInCharge = count($data['personInCharge']);
            $countEmployees = count($data['employees']);

            $persons = array();
            $i = 0;

            for($j=0; $j<$countPersonInCharge; $j++) {
                $persons[$i]['activity_id'] = $data['activity_id'];
                $persons[$i]['duty_id'] = $this->dutyPemapar;
                $persons[$i]['user_id'] = $data['personInCharge'][$j];
                $i++;
            }
            for($j=0; $j<$countEmployees; $j++) {
                $persons[$i]['activity_id'] = $data['activity_id'];
                $persons[$i]['duty_id'] = $this->dutyPeserta;
                $persons[$i]['user_id'] = $data['employees'][$j];
                $i++;
            }

            $this->Letter->Activity->ActivitiesUser->create();

            if($this->Letter->Activity->ActivitiesUser->saveMany($persons)) {
                return true;
            }
        }
        return false;
    }

    private function addExposeAddToLetters($data) {
        if(!empty($data)) {
            $this->Letter->create();

            if($this->Letter->save($data)) {
                return true;
            }
        }
        return false;
    }

    private function addExposeAddToEvidences($data) {
        if(!empty($data)) {
            $this->Letter->Activity->Evidence->create();

            if($this->Letter->Activity->Evidence->save($data)) {
                return true;
            }
        }
        return false;
    }

    private function addExposeCreatePdf($date = null, $description = null, $officerIds = null, $userIds = null, $fileName = null) {
        //variable to changed
        $arrDate = explode('-', $date);
        $month = $this->monthTranslation[(int)$arrDate[1]]['indonesianLong'];
        $allId = array_merge($officerIds, $userIds);
        $city = $this->city;

        $officers = $this->Letter->Uploader->User->Usercareerview->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'Usercareerview.id' => $officerIds,
                'Usercareerview.levelactive' => true,
                'Usercareerview.roleactive' => true,
                'Usercareerview.departementactive' => true,
                'Usercareerview.levelend' => null,
                'Usercareerview.roleend' => null
            ),
            'order' => array(
                'Usercareerview.role_id DESC',
                'Usercareerview.level_id DESC',
                'Usercareerview.name ASC'
            )
        ));

        $users = $this->Letter->Uploader->User->Usercareerview->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'Usercareerview.id' => $userIds,
                'Usercareerview.levelactive' => true,
                'Usercareerview.roleactive' => true,
                'Usercareerview.departementactive' => true,
                'Usercareerview.levelend' => null,
                'Usercareerview.roleend' => null,
                'NOT' => array('Usercareerview.id' => $officerIds)
            ),
            'order' => array(
                'Usercareerview.role_id DESC',
                'Usercareerview.level_id DESC',
                'Usercareerview.name ASC'
            )
        ));

        //for master of the office
        $this->Letter->Departement->ChiefsDepartement->unbindModel(array(
            'belongsTo' => array(
                'Departement'
            )
        ));
        $master = $this->Letter->Departement->ChiefsDepartement->find('first', array(
            'recursive' => 2,
            'conditions' => array(
                'ChiefsDepartement.departement_id' => $this->departementPerwakilan,
                'ChiefsDepartement.end' => null,
                'ChiefsDepartement.active' => true
            )
        ));

        //for departement to send
        $departements = $this->Letter->Departement->Userdepartementview->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'Userdepartementview.user_id' => $officerIds,
                'Userdepartementview.active' => true
            ),
            'fields' => array('Userdepartementview.departementdescription'),
            'group' => array('Userdepartementview.departement_id'),
            'order' => array('Userdepartementview.departementdescription ASC')
        ));

        $roles = $this->Letter->Departement->User->Userroleview->find('all', array(
            'recursive' => -1,
            'conditions' => array(
                'Userroleview.user_id' => $allId,
                'Userroleview.active' => true
            ),
            'fields' => array('Userroleview.rolename'),
            'group' => array('Userroleview.role_id'),
            'order' => array('Userroleview.role_id ASC')
        ));

        $numberFormat = $this->letterSP2FormatNo;
        $this->set(compact('date','arrDate', 'month', 'description', 'officers', 'users', 'city', 'master', 'departements', 'roles', 'fileName', 'numberFormat'));

        $this->layout = '/pdf/default';

        $this->render('/Pdf/add_expose_draft');
    }

    public function isLetterNotExists() {
        $description = trim(strtolower($this->request->data['description']));
        $description = '%' . $description . '%';
        $start = trim($this->request->data['start']);

        empty($start) ? $start = date('Y-m-d') : $start = $start;

        $countData = $this->Letter->Activity->find('count', array(
            'conditions' => array(
                'Activity.active' => 1,
                'Activity.draft' => 0,
                'Activity.start' => $start,
                'Activity.description LIKE' => $description
            )
        ));

        $countData > 0 ? $data = false : $data = true;

        $this->set(compact('data'));
        $this->set('_serialize', 'data');
    }

/**
 * CREATE VIEW userlevelviews AS SELECT lu.id AS id, lu.level_id AS level_id, lu.user_id AS user_id, lu.start AS start, lu.end AS end, lu.active AS active, u.name AS name, u.active AS useractive, l.name AS levelname, l.description AS leveldescription, l.active AS levelactive
 */
}